import {
  SiTailwindcss,
  SiNextdotjs,
  SiReact,
  SiJavascript,
  SiTypescript,
  SiPython,
  SiDjango,
  SiMongodb,
  SiFirebase,
  SiHtml5,
  SiCss3,
  SiBootstrap,
  SiGit,
  SiGithub,
  SiRedux,
  SiExpress,
  SiVuedotjs,
  SiAngular,
  SiGraphql,
  SiPostgresql,
  SiMysql,
  SiSass,
  SiWebpack,
  SiBabel,
  SiDocker,
  SiKubernetes,
  SiJenkins,
  SiAzuredevops,
  SiNginx,
  SiJest,
  SiVite,
  SiRedis,
  SiPhp,
  SiLaravel,
  SiDotnet,
  SiPrisma,
} from "react-icons/si";
import { FaNodeJs, FaAws, FaGitlab } from "react-icons/fa";
import { TbApi } from "react-icons/tb";

const iconMap = {
  prisma: <SiPrisma />,
  api: <TbApi />,
  react: <SiReact />,
  nextjs: <SiNextdotjs />,
  tailwind: <SiTailwindcss />,
  nodejs: <FaNodeJs />,
  javascript: <SiJavascript />,
  typescript: <SiTypescript />,
  python: <SiPython />,
  django: <SiDjango />,
  mongodb: <SiMongodb />,
  firebase: <SiFirebase />,
  html5: <SiHtml5 />,
  css3: <SiCss3 />,
  bootstrap: <SiBootstrap />,
  git: <SiGit />,
  github: <SiGithub />,
  gitlab: <FaGitlab />,
  redux: <SiRedux />,
  express: <SiExpress />,
  vue: <SiVuedotjs />,
  angular: <SiAngular />,
  graphql: <SiGraphql />,
  postgresql: <SiPostgresql />,
  mysql: <SiMysql />,
  aws: <FaAws />,
  azure: <SiAzuredevops />,
  sass: <SiSass />,
  webpack: <SiWebpack />,
  babel: <SiBabel />,
  docker: <SiDocker />,
  kubernetes: <SiKubernetes />,
  jenkins: <SiJenkins />,
  nginx: <SiNginx />,
  jest: <SiJest />,
  vite: <SiVite />,
  redis: <SiRedis />,
  php: <SiPhp />,
  laravel: <SiLaravel />,
  dotnet: <SiDotnet />,
};

export default iconMap;
