name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      - name: Deploy to cPanel
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          port: ${{ secrets.CPANEL_PORT }}
          script: |
            cd /home/aldinowi/sandri.my.id
            rm -rf *
            unzip -o ../../master.zip
